# Generated by Django 5.0.5 on 2024-05-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceresponse',
            name='previous_choice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
